
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 5.3
 PARAMETER PROC_INSTANCE = mb_JB_mb_1
 PARAMETER stdin = mdm_1
 PARAMETER stdout = mdm_1
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 2.3
 PARAMETER HW_INSTANCE = mb_JB_mb_1
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.0
 PARAMETER HW_INSTANCE = btns_gpio
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = PMOD_IO_Switch_IP
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = mb_JB_mb1_PMOD_IO_Switch_IP
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.0
 PARAMETER HW_INSTANCE = mb_JB_mb1_gpio
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = iic
 PARAMETER DRIVER_VER = 3.1
 PARAMETER HW_INSTANCE = mb_JB_mb1_iic
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.0
 PARAMETER HW_INSTANCE = mb_JB_mb1_lmb_lmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = mb_JB_mb1_spi
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = PMOD_IO_Switch_IP
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = mb_JC_mb2_PMOD_IO_Switch_IP
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.0
 PARAMETER HW_INSTANCE = mb_JC_mb2_gpio
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = iic
 PARAMETER DRIVER_VER = 3.1
 PARAMETER HW_INSTANCE = mb_JC_mb2_iic
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = mb_JC_mb2_spi
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = PMOD_IO_Switch_IP
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = mb_JD_mb3_PMOD_IO_Switch_IP
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.0
 PARAMETER HW_INSTANCE = mb_JD_mb3_gpio
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = iic
 PARAMETER DRIVER_VER = 3.1
 PARAMETER HW_INSTANCE = mb_JD_mb3_iic
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = mb_JD_mb3_spi
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = PMOD_IO_Switch_IP
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = mb_JE_mb4_PMOD_IO_Switch_IP
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.0
 PARAMETER HW_INSTANCE = mb_JE_mb4_gpio
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = iic
 PARAMETER DRIVER_VER = 3.1
 PARAMETER HW_INSTANCE = mb_JE_mb4_iic
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = mb_JE_mb4_spi
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.1
 PARAMETER HW_INSTANCE = mdm_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.0
 PARAMETER HW_INSTANCE = swsleds_gpio
END


